Revert "dont build tools because of undefined reference to ff_aom_uninit_film_grain_params"
This reverts commit 41b062ee48107898b4d00e483c88ae0aea39e91f.